In [22]:
import json
import requests
import pandas as pd 
import csv

url = 'https://merolagani.com/handlers/webrequesthandler.ashx?type=get_company_graph&symbol=SRBL&dateRange=300'
content = requests.get(url)
contents = content.text
json_acceptable_string = contents.replace("'", "\"")
data = json.loads(json_acceptable_string)
datas = data.get('quotes')
open = []
high = []
low = []
close = []
volume = []
rsi = []
date = []

for i in range(len(datas)):
    new_open = datas[i].get('open')
    open.append(new_open)
    
    new_high = datas[i].get('high')
    high.append(new_high)
    
    new_low = datas[i].get('low')
    low.append(new_low)
    
    new_close = datas[i].get('close')
    close.append(new_close)
    
    new_volume = datas[i].get('volume')
    volume.append(new_volume)
    
    new_rsi = datas[i].get('rsi')
    rsi.append(new_rsi)
    
    new_date = datas[i].get('date')
    date.append(new_date)
    
    
df = pd.DataFrame({'Date':date,'Open':open,'Close':close,'High':high,'Low':low,'Volume':volume,'RSI':rsi})

In [23]:
df

            Date   Open  Close   High    Low   Volume    RSI
0     01/30/2002  398.0  230.0  231.0  227.0   9526.0   0.00
1     11/03/2009  230.0  450.0  499.0  441.0   1180.0   0.00
2     11/04/2009  450.0  431.0  441.0  422.0   9010.0   0.00
3     11/05/2009  431.0  455.0  455.0  410.0   5860.0   0.00
4     11/08/2009  455.0  455.0  460.0  440.0  10360.0   0.00
5     11/09/2009  455.0  448.0  460.0  446.0   7680.0   0.00
6     11/10/2009  448.0  438.0  456.0  437.0   6350.0   0.00
7     11/11/2009  438.0  432.0  445.0  428.0   5530.0   0.00
8     11/12/2009  432.0  430.0  430.0  404.0   5210.0   0.00
9     11/15/2009  430.0  425.0  434.0  419.0   4350.0   0.00
10    11/16/2009  425.0  410.0  420.0  409.0   6410.0   0.00
11    11/17/2009  410.0  410.0  412.0  400.0   3860.0   0.00
12    11/18/2009  410.0  411.0  415.0  402.0   5160.0   0.00
13    11/19/2009  411.0  413.0  420.0  399.0   3440.0   0.00
14    11/22/2009  413.0  416.0  418.0  410.0   2410.0  51.57
15    11/23/2009  416.0  400.0  412.0  398.0   3120.0  49.78
16    11/24/2009  400.0  390.0  399.0  390.0   5000.0  48.64
17    11/25/2009  390.0  392.0  396.0  380.0   3330.0  48.89
18    11/26/2009  392.0  385.0  394.0  383.0   4560.0  48.00
19    11/30/2009  385.0  366.0  392.0  361.0   3590.0  45.59
20    12/01/2009  366.0  363.0  365.0  351.0   3730.0  45.20
21    12/03/2009  363.0  355.0  362.0  348.0   3900.0  44.13
22    12/06/2009  355.0  367.0  367.0  349.0   5990.0  46.20
23    12/07/2009  367.0  402.0  403.0  349.0   3670.0  51.80
24    12/08/2009  402.0  416.0  422.0  400.0   3810.0  53.86
25    12/09/2009  416.0  421.0  425.0  405.0   9850.0  54.61
26    12/10/2009  421.0  429.0  437.0  419.0  11400.0  55.85
27    12/13/2009  429.0  420.0  435.0  410.0   2490.0  54.07
28    12/14/2009  420.0  429.0  433.0  422.0   3630.0  55.59
29    12/15/2009  429.0  420.0  431.0  400.0   4080.0  53.67
...          ...    ...    ...    ...    ...      ...    ...
2220  08/04/2019  249.0  248.0  250.0  247.0  12866.0  43.96
2221  08/05/2019  247.0  249.0  249.0  247.0   1745.0  45.73
2222  08/06/2019  249.0  245.0  249.0  245.0  13490.0  40.25
2223  08/07/2019  244.0  245.0  247.0  244.0   6565.0  40.25
2224  08/08/2019  245.0  242.0  246.0  242.0   3678.0  36.44
2225  08/11/2019  239.0  241.0  242.0  239.0  14010.0  35.25
2226  08/12/2019  240.0  241.0  245.0  239.0  11588.0  35.25
2227  08/13/2019  243.0  244.0  244.0  239.0   2805.0  41.88
2228  08/14/2019  242.0  237.0  242.0  235.0  12848.0  33.31
2229  08/15/2019  238.0  233.0  238.0  232.0  12750.0  29.58
2230  08/18/2019  233.0  233.0  237.0  230.0  13554.0  29.58
2231  08/19/2019  234.0  237.0  239.0  231.0   7999.0  37.67
2232  08/20/2019  233.0  232.0  235.0  231.0   3410.0  32.62
2233  08/21/2019  232.0  232.0  234.0  232.0   3650.0  32.62
2234  08/22/2019  232.0  235.0  235.0  232.0   5572.0  38.37
2235  08/25/2019  231.0  231.0  233.0  229.0  10203.0  34.18
2236  08/26/2019  229.0  230.0  231.0  228.0   5236.0  33.21
2237  08/27/2019  230.0  232.0  234.0  230.0   4036.0  37.08
2238  08/28/2019  231.0  229.0  232.0  229.0   8799.0  33.91
2239  08/29/2019  230.0  230.0  235.0  227.0   7258.0  35.87
2240  09/01/2019  234.0  230.0  234.0  230.0   7458.0  35.87
2241  09/02/2019  230.0  230.0  230.0  226.0  13060.0  35.87
2242  09/03/2019  226.0  236.0  236.0  223.0  15988.0  47.57
2243  09/04/2019  233.0  240.0  241.0  230.0   8694.0  53.64
2244  09/05/2019  237.0  238.0  240.0  233.0   8911.0  50.50
2245  09/08/2019  236.0  232.0  236.0  232.0   7186.0  42.45
2246  09/09/2019  230.0  231.0  231.0  228.0  13450.0  41.26
2247  09/10/2019  227.0  230.0  230.0  227.0   3565.0  40.06
2248  09/11/2019  234.0  230.0  234.0  227.0   8749.0  40.06
2249  09/12/2019  230.0  228.0  230.0  227.0   4295.0  37.53

[2250 rows x 7 columns]

In [19]:
import numpy as np

In [20]:
np.shape(df)

(2250, 7)

In [21]:
df.to_csv(r'srbl.csv',index=None, header = True)